### ISSUE TITLE
Tesauro tipo luz 

### ISSUE THREAD

**Issue by opendatacaceres** [opencitydata/urbanismo-infraestructuras-farolas#14]
Crear un tesauro similar al de tipos de lámparas utilizadas en el alumbrado público, sobre los tipos de luz emitida, para cumplir con el skeleton de Open Refine para la transformación de los datos a RDF:

{ "uri": "http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/alumbrado-publico#emiteTipoDeLuz",
   "curie": "http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/alumbrado-publico#emiteTipoDeLuz",
   "target": {
        "nodeType": "cell-as-resource",
        "expression": **"\"http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/alumbrado-publico/tipo-luz/\"+value"**,
        "isRowNumberCell": false,
        "columnName": "tipoLuz",
        "rdfTypes": [],
        "links": []
    }
}

**Comment by ocorcho** [comment]
Now the vocabulary is being redone completely.
